<a href="https://colab.research.google.com/github/abhijithneilabraham/ExploreML/blob/master/Group10%20-Age%20classification%20/agedetection10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Parasgr7/Age-Detection-Indian-Actors-

Cloning into 'Age-Detection-Indian-Actors-'...
remote: Enumerating objects: 26096, done.
remote: Total 26096 (delta 0), reused 0 (delta 0), pack-reused 26096
Receiving objects: 100% (26096/26096), 57.17 MiB | 27.19 MiB/s, done.
Resolving deltas: 100% (7405/7405), done.
Checking out files: 100% (26550/26550), done.


In [2]:
%cd Age-Detection-Indian-Actors-


/content/Age-Detection-Indian-Actors-


In [14]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.misc import *
import os
import keras
from cv2 import imread,resize
from sklearn.preprocessing import LabelEncoder


Using TensorFlow backend.


In [4]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

ID   Class
0    377.jpg  MIDDLE
1  17814.jpg   YOUNG
2  21283.jpg  MIDDLE
3  16496.jpg   YOUNG
4   4487.jpg  MIDDLE

In [0]:
temp = []
for img_name in train.ID:
    img_path ='Train/'+img_name
    img = imread(img_path)
    img = resize(img, (64,64))
    img = img.astype('float32') # this will help us in later stage
    temp.append(img)

train_x = np.stack(temp)



In [0]:
temp = []
for img_name in test.ID:
    img_path = 'Test/'+img_name
    img = imread(img_path)
    img = resize(img, (64,64))
    img = img.astype('float32') # this will help us in later stage
    temp.append(img)


In [0]:
test_x = np.stack(temp)

train_x = train_x / 255.
test_x = test_x / 255.
train.Class.value_counts(normalize=True)

lb = LabelEncoder()
train_y = lb.fit_transform(train.Class)
train_y = keras.utils.np_utils.to_categorical(train_y)

[[[[4.45184827e-11 4.35910093e-11 4.73008854e-11]
   [4.35910093e-11 4.26635428e-11 4.63734190e-11]
   [4.08086065e-11 3.98811401e-11 4.17360764e-11]
   ...
   [2.78240517e-12 1.02021516e-11 3.70987399e-12]
   [5.56481033e-12 1.29845570e-11 6.49227850e-12]
   [4.63734173e-12 1.20570880e-11 5.56481033e-12]]

  [[4.54459526e-11 4.45184827e-11 4.73008854e-11]
   [4.35910093e-11 4.26635428e-11 4.54459526e-11]
   [3.98811401e-11 3.89536736e-11 4.08086065e-11]
   ...
   [7.41974798e-12 1.48394960e-11 9.27468345e-12]
   [1.02021516e-11 1.66944323e-11 1.11296207e-11]
   [9.27468345e-12 1.66944323e-11 1.11296207e-11]]

  [[5.19382280e-11 5.10107616e-11 5.28656945e-11]
   [4.82283519e-11 4.82283519e-11 5.00832951e-11]
   [4.54459526e-11 4.45184827e-11 4.63734190e-11]
   ...
   [1.57669624e-11 2.22592413e-11 1.66944323e-11]
   [1.66944323e-11 2.31867095e-11 1.85493669e-11]
   [1.57669624e-11 2.22592413e-11 1.76219005e-11]]

  ...

  [[1.29845579e-10 1.40975204e-10 1.15006081e-10]
   [1.21498367e-